development:
  adapter: mysql2
  database: careyfer_development
  encoding: utf8
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: careyfer_test
  encoding: utf8
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: careyfer_production
  encoding: utf8
  username: root
  password:
  host: localhost
